name: mediqcm
description: qcm medicaux

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
version: 1.0.0+1

environment:
  sdk: ">=2.18.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

  #flutter pub add go brrrrr
  flutter_native_splash: ^2.2.16
  flutter_launcher_icons: ^0.11.0
  responsive_framework: ^0.2.0
  adaptive_theme: ^3.1.1
  firebase_core: ^2.4.0
  firebase_auth: ^4.2.1
  cloud_firestore: ^4.2.0
  animations: ^2.0.7
  url_launcher: ^6.1.7
  font_awesome_flutter: ^10.3.0
  firebase_storage: ^11.0.8
  flutter_riverpod: ^2.1.1



dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:

  # the material Icons class.
  uses-material-design: true

  # custom fonts
  fonts:
    - family: Anton
      fonts:
        - asset: assets/fonts/Anton-Regular.ttf
          style: normal
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
          style: normal


  # images and stuff
  assets:
    - assets/images/icon.png
    - assets/images/logo.png
    - assets/images/logo-dark.png

